src/Jeuci.SalesSystem.AdminWeb/Areas/Sales/Controllers/SalesSoftwareController.cs
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using Abp.Application.Services.Dto;
using Abp.UI;
using Jeuci.SalesSystem.AdminWeb.Controllers.ControllerBases;
using Jeuci.SalesSystem.Brands;
using Jeuci.SalesSystem.Brands.Dtos;
using Jeuci.SalesSystem.Entities.Common.Enums;
using Jeuci.SalesSystem.Sales;
using Jeuci.SalesSystem.Sales.Dtos;
using Jeuci.SalesSystem.SoftServices;
using Jeuci.SalesSystem.SoftServices.Dtos;

namespace Jeuci.SalesSystem.AdminWeb.Areas.Sales.Controllers
{
    public class SalesSoftwareController : AuthorizeControllerBase
    {
        private readonly IBrandAppService _brandAppService;
        private readonly IServiceInfoAppService _serviceInfoAppService;
        private readonly ISaleSoftwareAppService _saleSoftwareAppService;

        public SalesSoftwareController(IBrandAppService brandAppService,
            IServiceInfoAppService serviceInfoAppService, ISaleSoftwareAppService saleSoftwareAppService)
        {
            _brandAppService = brandAppService;
            _serviceInfoAppService = serviceInfoAppService;
            _saleSoftwareAppService = saleSoftwareAppService;
        }

        // GET: Sales/SalesSoftware
        public async Task<ActionResult> Index()
        {
            var currentUserBrandList = await _brandAppService.GetBrandsByCurrentUserBrandIds(CurrentUserInfo.Brands);
            return View(currentUserBrandList);
        }
    
        public ActionResult SalesService(int id)
        {
            var serviceInfo = _serviceInfoAppService.Get(new IdInput() {Id = id});
            return PartialView("_SalesService", serviceInfo);
        }

        [HttpPost]
        public async Task<JsonResult> SalesService(SalesInput model)
        {
          //  CheckModelState();

            var result = await _saleSoftwareAppService.SalesSoftwareService(model,CurrentUserInfo.Id);
            switch (result.SalesResultType)
            {
                case SalesResultType.Success:
                    return Json(result);
                default:
                    throw  new UserFriendlyException("授权失败", result.Message);
            }
        }

        public async Task<ActionResult> Record()
        {
            var brandList = await _brandAppService.GetBrandsByCurrentUserBrandIds(CurrentUserInfo.Brands);
            brandList.Add(new BrandInfoDto()
            {
                Id = -1,
                BrandName = "所有品牌"
            });

            ViewBag.BrandList = brandList.OrderBy(p=>p.Id).Select(a => new SelectListItem()
            {
                Text = a.BrandName,
                Value = a.Id.ToString(),
                Selected = a.Id ==-1
            });

            var serviceInfoList = await _serviceInfoAppService.GetAllServiceInfoList();
            serviceInfoList.Add(new ServiceInfoDto()
            {
                Id = -1,
                BrandId = -1,
                ServiceName = "所有产品"

            });
            ViewBag.ServiceInfoList = serviceInfoList.OrderBy(p => p.Id).Select(a => new SelectListItem()
            {
                Text = a.ServiceName,
                Value = a.Id.ToString(),
                Selected = a.Id == -1
            });
            
            return View();
        }

    }
}

src/Jeuci.SalesSystem.AdminWeb/Areas/Sales/Views/SalesSoftware/Index.cshtml
@model IList<Jeuci.SalesSystem.Brands.Dtos.BrandInfoDto>

@{
    ViewBag.Title = "SaleSoftwareIndex";
    ViewBag.ActiveMenu = "SaleSoftwareRecord";
    var count = 1;
}
@section Scripts{
    <script src="~/Scripts/sales/SalesDialog.js"></script>
    <script src="~/Abp/Lib/jquery.serializeJSON/jquery.serializejson.min.js"></script>
   
}

<div class="row">
    <div class="row">
        <div class="col-lg-12">
            <h3 class="page-header">销售</h3>
        </div>
        <!-- /.col-lg-12 -->
    </div>

    <div class="col-lg-12">
        <div class="panel-group" id="accordion">
            @foreach (var brandItem in Model)
            {
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h2 class="panel-title">
                            <a data-toggle="collapse" data-parent="#accordion" href="#@Html.Raw("collapse"+count)">@brandItem.BrandName</a>
                        </h2>
                    </div>
                    <div id="@Html.Raw("collapse"+count)" class="@Html.Raw(count == 1 ?"panel-collapse collapse in":"panel-collapse collapse")">
                        <div class="panel-body">
                            <div class="row">
                                @foreach (var lotterySeed in brandItem.ServiceInfos)
                                {
                                    <div class="col-sm-2">
                                        <a href="javascript:void(0)" id="@lotterySeed.Id" class="btn btn-primary lottery-seed" data-url="@Url.Action("SalesService","SalesSoftware",new {area="Sales"})" data-toggle="modal" data-target="#myModal">
                                            @lotterySeed.ServiceName
                                        </a>
                                    </div>
                                }
                            </div>
                            </div>
                    </div>
                </div>
                count++;
            }
          
        </div>
    </div>
</div>

src/Jeuci.SalesSystem.AdminWeb/Areas/Sales/Views/SalesSoftware/Record.cshtml
@{
    ViewBag.Title = "SaleSoftwareRecord";
    ViewBag.ActiveMenu = "SaleSoftwareRecord";
}

@section styles{
    <link rel="stylesheet" href="~/Abp/Lib/bootstrap-table/dist/bootstrap-table.min.css">
    <link rel="stylesheet" href="~/Abp/Lib/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css">
    <link rel="stylesheet" href="~/Abp/Lib/bootstrap-daterangepicker/daterangepicker.css">
    <link rel="stylesheet" href="~/Content/salesyscss/custom.css"/>
}

@section Scripts{
    <script src="~/Abp/Lib/jquery.serializeJSON/jquery.serializejson.min.js"></script>
    <script src="~/Abp/Lib/bootstrap-table/dist/bootstrap-table.min.js"></script>
    <script src="~/Abp/Lib/bootstrap-table/dist/locale/bootstrap-table-zh-CN.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.11.2/moment.min.js"></script><!--using cdn server-->
    <script src="~/Abp/Lib/bootstrap-daterangepicker/daterangepicker.js"></script>
    <script src="~/Abp/Lib/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js"></script>
    <script src="~/Abp/Lib/bootstrap-datepicker/dist/locales/bootstrap-datepicker.zh-CN.min.js"></script>
    <script src="~/Scripts/others/data-format.js"></script>

}
<div class="row">
    <div class="row title">
        <div class="col-sm-12">
            <h3 class="page-header">销售记录</h3>
        </div>
    </div>
    <div class="col-sm-12">
        <div id="toolbar">
            <div class="form-inline" role="form">
                <div class="form-group">
                    <label for="brandList">品牌: </label>
                    @Html.DropDownList("BrandList", null, new { @class = "form-control input-sm", id = "Brand" })
                </div>
                <div class="form-group">
                    <label for="serviceInfoList">产品: </label>
                    @Html.DropDownList("ServiceInfoList", null, new { @class = "form-control input-sm ", id = "ServiceInfo" })
                </div>
                <div class="form-group">
                    <label>日期范围: </label>
                    <div class="input-group">
                        <div class="input-group-addon">
                            <i class="fa fa-calendar"></i>
                        </div>
                        <input type="text" id="reservation" name="reservation" class="form-control pull-right input-sm">
                    </div>
                </div>
                <div class="form-group">
                    <label>订单号: </label>
                    <input id="orderId" name="orderId" class="form-control input-sm " type="text">
                </div>
            </div>
            <div class="form-inline" role="form">

                <div class="form-group">
                    <label>客户通行证: </label>
                    <input name="userPassport" class="form-control input-sm " type="text">
                </div>
                <div class="form-group">
                    <label>代理商: </label>
                    <input name="Agent" class="form-control input-sm " type="text">
                </div>
                <div class="form-group">
                    <label>销售: </label>
                    <input name="SalesAdmin" class="form-control input-sm " type="text">
                </div>

                <div class="form-group">
                    <a href="#" class="btn btn-link"><i class=""></i>前一天</a>
                    <a href="#" class="btn btn-link"><i class=""></i>后一天</a>
                </div>
                <button id="search" class="btn btn-info btn-sm" type="button">
                    <i class="fa fa-search"></i>筛选数据
                </button>
            </div>
        </div>

        <table id="table"
               data-toggle="table"
               data-toolbar="#toolbar"
               data-show-refresh="true"
               data-show-toggle="true"
               data-show-columns="true"
               data-query-params="queryParams"
               data-pagination="true"
               data-page-size="50"
               data-page-list="[50,100,200]"
               data-side-pagination="server"
               data-method="get"
               data-row-style="rowStyle"
               data-url="/api/SalesRecord/GetList">
            <thead>
                <tr>
                    <th data-field="id">单号</th>
                    <th data-field="serviceName">服务名称</th>
                    <th data-field="userPassport">用户通行证</th>
                    <th data-field="cost" data-formatter="moneyFomatter">销售价</th>
                    <th data-field="profit" data-formatter="moneyFomatter">利润</th>
                    <th data-field="salesDateTime" data-formatter="dateFomatter">销售日期</th>
                    <th data-field="authExpiration" data-formatter="dateFomatter">有效期</th>
                    <th data-field="agentUserName">代理商</th>
                    <th data-field="adminUserName">销售</th>
                    <th data-field="remarks">备注</th>
                    <th data-field="orderState" data-formatter="operateFormatter"
                        data-width="60px" data-events="operateEvents">操作</th>
                </tr>
            </thead>

        </table>
    </div>
</div>

<script type="text/javascript">
    var $table = $('#table'),
        $search = $('#search');

    function queryParams(params) {
        $('#toolbar')
            .find('input[name]')
            .each(function () {
                params[$(this).attr('name')] = $(this).val();
            });
        $('#toolbar')
            .find('select[name]')
            .each(function () {
                params[$(this).attr('id')] = $(this).val();
            });
        return params;
    }

    function dateFomatter(value) {
        return new Date(value).pattern('yyyy-MM-dd hh:mm:ss');
    }

    function moneyFomatter(value) {
        return value.formatMoney(2, " ¥", ".", ",")
    }

    function operateFormatter(value, row, index) {
        if (value === 2) {
            return [
                '<a class="undo" href="javascript:void(0)" title="undo">',
                '<i class="fa fa-undo"></i>',
                '撤销',
                '</a>'
            ].join('');
        }

    }

    function responseHandler(res) {
        return res.rows;
    }

    function getHeight() {
        return $(window).height() - $('.title').outerHeight(true);
    }

    function rowStyle(row, index) {
        var classes = ['active', 'success', 'info', 'warning', 'danger'];
        if (row['orderState'] === 2) {
            return {
                classes: classes[2]
            };
        }
        //if (row['orderState'] === 1) {
        //    return {
        //        classes: classes[2]
        //    };
        //}
        if (row['orderState'] === 0) {
            return {
                classes: classes[4]
            };
        }
        return {};
    }

    window.operateEvents = {
        'click .undo': function (e, value, row, index) {
            abp.message.confirm("您确定要撤销单号为" + row['id'] + "的订单吗?","撤销订单", function (isConfirmed) {
                if (isConfirmed) {
                    console.log(row['id']);
                    $.ajax({
                        url: '/api/SalesRecord/'+row['id'],
                        type: 'PUT',
                        contentType: "application/json; charset=utf-8",
                        //data: { 'id': row["id"] },   /*注意路由匹配规则*/
                        datatype: 'json',
                        success: function (data) {
                            debugger;
                            if (data['code'] === 200) {
                                abp.notify.success(data['data'], data['msg']);
                                $table.bootstrapTable('refresh');
                            } else {
                                abp.notify.error("订单撤销失败,详情:" + data['Data'], data['msg']);
                            }
                        },
                        error: function (xhr) {
                            abp.notify.error("订单撤销失败，服务器内部错误,详情:" + xhr.responseText);
                        }
                    });

                }
            });
        }
    }

    $(function () {

        $('#reservation').daterangepicker();

        $table.bootstrapTable({
            height: getHeight()
            //pageList:"[50,20,40,100]",
        });

        $search.click(function () {
            $table.bootstrapTable('refresh');
        });
    });



</script>

src/Jeuci.SalesSystem.AdminWeb/Areas/Sales/Views/SalesSoftware/_SalesService.cshtml
@model Jeuci.SalesSystem.SoftServices.Dtos.ServiceInfoDto
@{
    var count = 1;
}

<script src="~/Scripts/sales/SelasConfirm.js"></script>

<link href="~/Content/bootstrap.min.css" rel="stylesheet"/>
@*<link href="~/Content/toastr.min.css" rel="stylesheet"/>*@
<link href="~/Scripts/sweetalert/sweet-alert.css" rel="stylesheet"/>

<div class="modal-content">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">@Model.ServiceName</h4>
    </div>
    @using (Html.BeginForm("", "", FormMethod.Post, new {role = "form", id="form1", @class = "form-horizontal"}))
    {
        <div class="modal-body" style="overflow-x: hidden; overflow-y: auto; max-height: 490px;">
            <div class="row hidden">
                @Html.Hidden("ServiceId",Model.Id)
            </div>
            <div class="row">
                <div class="col-sm-12">
                    <div class="panel panel-info">
                        <div class="panel-heading">
                            软件版本
                        </div>
                        <div class="table-responsive">
                            <table class="table table-condensed table-hover">
                                <tbody>
                                @foreach (var servicePrice in Model.ServicePrices)
                                {
                                    <tr>
                                        <td>@count</td>
                                        <td>@servicePrice.AuthDesc</td>
                                        <td>@servicePrice.Price</td>
                                        <td>
                                            @Html.RadioButton("ServicePriceId", servicePrice.Id, count == 1)
                                        </td>
                                    </tr>
                                    count++;
                                }
                                </tbody>
                            </table>
                        </div>

                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12">
                    <div class="panel panel-info">
                        <div class="panel-heading">
                            授权
                        </div>
                        <div class="panel-body">
                            <div class="form-group">
                                @Html.Label("通行证", new {@class = "col-sm-2 control-label"})
                                <div class="col-sm-9">
                                    @Html.TextBox("Passport", null, new {@class = "form-control"})
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.Label("销售价格", new {@class = "col-sm-2 control-label"})
                                <div class="col-sm-9">
                                    @Html.TextBox("Cost", null, new {@class = "form-control"})
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.Label("备注", new {@class = "col-sm-2 control-label"})
                                <div class="col-sm-9">
                                    @Html.TextArea("Remarks", null, new {@class = "form-control"})
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
            <button id="btn-confirm" type="button" class="btn btn-primary">确认</button>
        </div>
    }

</div>

<!-- /.modal-content -->